-- require('user.bufferline')
require('user.colors')
require('user.copilot')
require('user.fonts')
require('user.gitsigns')
require('user.lsp')
require('user.lualine')
-- require('user.nvim-tree')
require('user.packer')
require('user.remap')
require('user.lspsaga')
require('user.set')
require('user.telescope')
require('user.treesitter')
